---
name: Zbuduj projekt

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Build
        run: dotnet build --configuration Release
        working-directory: DumbAPI

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dumbapi
          path: DumbAPI/bin/Release/net8.0
